export interface ExamPreset {
  id: string;
  name: string;
  exam: string;
  type: "photo" | "signature" | "thumb";
  width: number;
  height: number;
  minKB: number;
  maxKB: number;
  bgColor: string | null;
  format: "jpeg" | "png";
  dpi: number;
  requiresDateStamp: boolean;
  note: string;
  officialUrl: string;
  category: string;
  searchKeywords: string[];
}

export const CATEGORIES = [
  "SSC",
  "UPSC",
  "Banking",
  "Railway",
  "Medical/Engineering",
  "ID/Passport",
  "Postal",
  "State PSC",
  "Custom",
] as const;

export const PRESETS: ExamPreset[] = [
  // ========== SSC ==========
  {
    id: "ssc-cgl-photo",
    name: "SSC CGL/CHSL/MTS Photo",
    exam: "SSC",
    type: "photo",
    width: 100,
    height: 120,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: true,
    note: "3.5cm x 4.5cm, 20-50KB, white bg, name+date required",
    officialUrl: "https://ssc.gov.in",
    category: "SSC",
    searchKeywords: ["ssc cgl photo size", "ssc chsl photo resize", "ssc mts photo 50kb"],
  },
  {
    id: "ssc-signature",
    name: "SSC Signature",
    exam: "SSC",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "4.0cm x 2.0cm, 10-20KB, black ink on white paper",
    officialUrl: "https://ssc.gov.in",
    category: "SSC",
    searchKeywords: ["ssc signature size", "ssc signature 20kb", "ssc signature resize"],
  },

  // ========== UPSC ==========
  {
    id: "upsc-photo",
    name: "UPSC Civil Services Photo",
    exam: "UPSC",
    type: "photo",
    width: 350,
    height: 350,
    minKB: 30,
    maxKB: 100,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "350x350px, 30-100KB, white bg (OTR registration)",
    officialUrl: "https://upsconline.nic.in",
    category: "UPSC",
    searchKeywords: ["upsc photo size", "upsc otr photo", "upsc 350x350"],
  },
  {
    id: "upsc-signature",
    name: "UPSC Signature",
    exam: "UPSC",
    type: "signature",
    width: 350,
    height: 150,
    minKB: 20,
    maxKB: 300,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "350x150px, 20-300KB",
    officialUrl: "https://upsconline.nic.in",
    category: "UPSC",
    searchKeywords: ["upsc signature size", "upsc signature resize"],
  },

  // ========== BANKING (IBPS/SBI) ==========
  {
    id: "ibps-sbi-photo",
    name: "IBPS/SBI Bank Exam Photo",
    exam: "IBPS/SBI",
    type: "photo",
    width: 200,
    height: 230,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "200x230px, 20-50KB, white bg",
    officialUrl: "https://ibps.in",
    category: "Banking",
    searchKeywords: ["ibps photo size", "sbi po photo resize", "bank exam photo 50kb"],
  },
  {
    id: "ibps-sbi-signature",
    name: "IBPS/SBI Signature",
    exam: "IBPS/SBI",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB, black ink on white",
    officialUrl: "https://ibps.in",
    category: "Banking",
    searchKeywords: ["ibps signature size", "sbi signature 20kb"],
  },
  {
    id: "ibps-sbi-thumb",
    name: "IBPS/SBI Left Thumb",
    exam: "IBPS/SBI",
    type: "thumb",
    width: 240,
    height: 240,
    minKB: 20,
    maxKB: 50,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "240x240px, 20-50KB",
    officialUrl: "https://ibps.in",
    category: "Banking",
    searchKeywords: ["ibps thumb impression size"],
  },

  // ========== RAILWAY (RRB) ==========
  {
    id: "rrb-photo",
    name: "RRB Railway Photo",
    exam: "RRB",
    type: "photo",
    width: 350,
    height: 350,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: true,
    note: "3.5cm x 3.5cm (square), 20-50KB, white bg",
    officialUrl: "https://www.rrbcdg.gov.in",
    category: "Railway",
    searchKeywords: ["rrb photo size", "railway exam photo resize", "rrb group d photo"],
  },
  {
    id: "rrb-signature",
    name: "RRB Railway Signature",
    exam: "RRB",
    type: "signature",
    width: 350,
    height: 140,
    minKB: 20,
    maxKB: 50,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "5:2 ratio, 20-50KB",
    officialUrl: "https://www.rrbcdg.gov.in",
    category: "Railway",
    searchKeywords: ["rrb signature size", "railway signature 5:2 ratio"],
  },
  {
    id: "rrb-groupd-photo",
    name: "RRB Group D Photo",
    exam: "RRB Group D",
    type: "photo",
    width: 320,
    height: 240,
    minKB: 20,
    maxKB: 70,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "320x240px, 20-70KB, white bg",
    officialUrl: "https://www.rrbcdg.gov.in",
    category: "Railway",
    searchKeywords: ["rrb group d photo size"],
  },
  {
    id: "rrb-groupd-signature",
    name: "RRB Group D Signature",
    exam: "RRB Group D",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 30,
    maxKB: 70,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 30-70KB",
    officialUrl: "https://www.rrbcdg.gov.in",
    category: "Railway",
    searchKeywords: ["rrb group d signature size"],
  },

  // ========== MEDICAL/ENGINEERING ==========
  {
    id: "neet-photo",
    name: "NEET UG Photo",
    exam: "NEET",
    type: "photo",
    width: 276,
    height: 354,
    minKB: 10,
    maxKB: 200,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "Postcard ratio (3.5cm x 4.5cm), 10-200KB, white bg",
    officialUrl: "https://neet.nta.nic.in",
    category: "Medical/Engineering",
    searchKeywords: ["neet photo size", "neet ug photo resize", "neet postcard photo"],
  },
  {
    id: "jee-main-photo",
    name: "JEE Main Photo",
    exam: "JEE Main",
    type: "photo",
    width: 276,
    height: 354,
    minKB: 10,
    maxKB: 200,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "3.5cm x 4.5cm, 10-200KB, white bg",
    officialUrl: "https://jeemain.nta.ac.in",
    category: "Medical/Engineering",
    searchKeywords: ["jee main photo size", "jee photo resize"],
  },

  // ========== ID / PASSPORT ==========
  {
    id: "pan-card-photo",
    name: "PAN Card Photo (NSDL)",
    exam: "PAN Card",
    type: "photo",
    width: 132,
    height: 170,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "3.5cm x 2.5cm, 20-50KB, 200 DPI, white bg",
    officialUrl: "https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html",
    category: "ID/Passport",
    searchKeywords: ["pan card photo size", "nsdl pan photo resize", "pan card photo 50kb"],
  },
  {
    id: "pan-card-signature",
    name: "PAN Card Signature (NSDL)",
    exam: "PAN Card",
    type: "signature",
    width: 170,
    height: 76,
    minKB: 10,
    maxKB: 50,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "2cm x 4.5cm, 10-50KB, 200 DPI",
    officialUrl: "https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html",
    category: "ID/Passport",
    searchKeywords: ["pan card signature size", "nsdl signature resize"],
  },
  {
    id: "aadhaar-photo",
    name: "Aadhaar Card Photo",
    exam: "Aadhaar",
    type: "photo",
    width: 150,
    height: 200,
    minKB: 10,
    maxKB: 100,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "150x200px, 10-100KB, white bg",
    officialUrl: "https://uidai.gov.in",
    category: "ID/Passport",
    searchKeywords: ["aadhaar photo size", "aadhaar card photo resize"],
  },
  {
    id: "passport-india",
    name: "Indian Passport Photo",
    exam: "Passport",
    type: "photo",
    width: 413,
    height: 531,
    minKB: 20,
    maxKB: 300,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 300,
    requiresDateStamp: false,
    note: "2x2 inch (51x51mm), 20-300KB, white bg, 300 DPI",
    officialUrl: "https://portal2.passportindia.gov.in",
    category: "ID/Passport",
    searchKeywords: ["passport photo size india", "passport seva photo resize", "indian passport photo online"],
  },

  // ========== POSTAL ==========
  {
    id: "india-post-gds-photo",
    name: "India Post GDS Photo",
    exam: "India Post GDS",
    type: "photo",
    width: 200,
    height: 250,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "4:5 ratio, 200x250px, 20-50KB",
    officialUrl: "https://indiapostgdsonline.gov.in",
    category: "Postal",
    searchKeywords: ["india post gds photo size", "gds photo resize"],
  },
  {
    id: "india-post-gds-signature",
    name: "India Post GDS Signature",
    exam: "India Post GDS",
    type: "signature",
    width: 300,
    height: 120,
    minKB: 10,
    maxKB: 30,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "5:2 ratio, 10-30KB",
    officialUrl: "https://indiapostgdsonline.gov.in",
    category: "Postal",
    searchKeywords: ["gds signature size", "india post gds signature resize"],
  },

  // ========== STATE PSC ==========
  {
    id: "kerala-psc-photo",
    name: "Kerala PSC (Thulasi) Photo",
    exam: "Kerala PSC",
    type: "photo",
    width: 200,
    height: 150,
    minKB: 10,
    maxKB: 30,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "200x150px, under 30KB",
    officialUrl: "https://thulasi.psc.kerala.gov.in",
    category: "State PSC",
    searchKeywords: ["kerala psc photo size", "thulasi photo resize"],
  },
  {
    id: "kerala-psc-signature",
    name: "Kerala PSC (Thulasi) Signature",
    exam: "Kerala PSC",
    type: "signature",
    width: 100,
    height: 150,
    minKB: 10,
    maxKB: 30,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "100x150px, under 30KB",
    officialUrl: "https://thulasi.psc.kerala.gov.in",
    category: "State PSC",
    searchKeywords: ["kerala psc signature size", "thulasi signature resize"],
  },

  // ========== CUSTOM ==========
  {
    id: "custom",
    name: "Custom Size",
    exam: "Custom",
    type: "photo",
    width: 200,
    height: 200,
    minKB: 10,
    maxKB: 100,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "Enter your own dimensions and KB range",
    officialUrl: "",
    category: "Custom",
    searchKeywords: ["custom photo resize", "resize image to kb"],
  },
];

export function getPresetById(id: string): ExamPreset | undefined {
  return PRESETS.find(p => p.id === id);
}

export function getPresetsByCategory(category: string): ExamPreset[] {
  return PRESETS.filter(p => p.category === category);
}

export function getPresetSlug(preset: ExamPreset): string {
  if (preset.type === "photo") {
    return `${preset.id.replace(/-photo$/, "")}-photo-resizer`;
  } else if (preset.type === "signature") {
    return `${preset.id.replace(/-signature$/, "")}-signature-resizer`;
  }
  return `${preset.id}-resizer`;
}
